import "../../css/integration.css";

import { CopyBlock, dracula } from "react-code-blocks";

export function Integration() {
  const code =
    '<script src="https://catchon-ethsf.vercel.app/static/js/main.js">\n</script><link href="https://catchon-ethsf.vercel.app/static/css/main.css" rel="stylesheet">';
  console.log("dracula: ", dracula);
  return (
    <>
      <h1>This is Integration!</h1>

      <div>
        <div className="step">
          <div className="leftPart">
            <span>Step 1.</span>
            <span>Choose a eCommerce wesite template at Webflow.</span>
          </div>
          <div className="rightPart"></div>
        </div>
        <div className="step">
          <div className="leftPart">
            <span>Step 2.</span>
            <span>
              Copy the script below, generated by CatchOn sepcially for your
              store.
            </span>
          </div>
          <div className="rightPart">
            <CopyBlock
              text={code}
              language="html"
              showLineNumbers={true}
              theme={dracula}
              codeBlock
            />
          </div>
        </div>
        <div className="step">
          <div className="leftPart">
            <span>Step 3.</span>
            <span>
              Paste the script in the hightlighted area. Then, launch your
              eCommerce and start erarning!
            </span>
          </div>
          <div className="rightPart"></div>
        </div>
      </div>
    </>
  );
}
