import "../../css/integration.css";
import top from "./script-top.png";
import bottom from "./script-bottom.png";
import { CodeBlock, dracula } from "react-code-blocks";
import { Button } from "@mui/material";

export function Integration() {
  const code =
    '<script src="https://catchon-ethsf.vercel.app/static/js/main.js">\n</script><link href="https://catchon-ethsf.vercel.app/static/css/main.css" rel="stylesheet">';
  console.log("dracula: ", dracula);
  return (
    <>
      <h1>No-Code Integration with Webflow</h1>

      <div>
        <div className="step">
          <div className="leftPart" sx={{ maxWidth: 300 }}>
            <span>Step 1.</span>
            <br />
            <span>Choose a eCommerce wesite template at Webflow.</span>
          </div>
          <div className="rightPart">
            <img src={top} alt="Italian Trulli" />
          </div>
        </div>
        <div className="step">
          <div className="leftPart" sx={{ maxWidth: 300 }}>
            <span>Step 2.</span>
            <br />
            <span>
              Copy the script below, generated by CatchOn sepcially for your
              store.
            </span>
          </div>
          <div className="rightPart">
            <CodeBlock
              text={code}
              language="html"
              showLineNumbers={true}
              theme={dracula}
              codeBlock
            />
            <Button
              id={"copy-button"}
              onClick={async () => {
                await navigator.clipboard.writeText(code);
                alert("Copied!");
              }}
            >
              Copy
            </Button>
          </div>
          <br />
        </div>
        <div className="step">
          <div className="leftPart" sx={{ maxWidth: 300 }}>
            <span>Step 3.</span>
            <br />
            <span>
              Paste the script in the hightlighted area. Then, launch your
              eCommerce and start erarning!
            </span>
          </div>
          <div className="rightPart">
            <img src={bottom} alt="Italian Trulli" />
          </div>
        </div>
      </div>
    </>
  );
}
